services:
#    jlam_horkos.example:
#        class: Jlam\HorkosBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


#jlam_horkos.twig.safe_divide:
#        class: Jlam\HorkosBundle\Twig\SafeDivideExtension
#        tags:
#            - { name: twig.extension }
